### ISSUE TITLE
How to Add Message Properties in Interceptor

### ISSUE THREAD

**Issue by JarrodJ83** [fsharplang-ru/pulsar-client-dotnet#113]
I looked around but I could not find any examples of interceptor implementations. If I missed any could you please direct me to them? 

I am trying to implement a diagnostic interceptor that will interact with `System.Diagnostic.Activity`. To do this I need to be able to inject new properties into the message properties. However, properties is a read-only collection. I looked at creating a new message with a new set of properties to return but the constructor for `producer.NewMessage` only takes a `string` Key value which doesn't match the value of the Key property on the MessageBuilder from the interceptor. 

What is the best approach to add properties to the outbound message?

**Comment by JarrodJ83** [comment]
Also I'd like to contribute this work back to the community if it works out and there is interest in it.

**Comment by Lanayx** [comment]
Hi, @JarrodJ83 ! Thanks for raising the issue, message immutability is intentional, [this is the way how it is supposed to be used now](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/ProducerInterceptor.fs#L36-L41) , however it seems to need some refactoring. I'll think how to improve it and give an update a bit later.

**Comment by JarrodJ83** [comment]
Thanks @Lanayx ! Much appreciated.

**Comment by Lanayx** [comment]
@JarrodJ83 We are merging a big feature - message encryption, hopefully a new version will be ready on Monday together with this small improvement

**Comment by Lanayx** [comment]
Closing as functionality was added in 1.5.0 release
