### ISSUE TITLE
Add CancellationToken support

### ISSUE THREAD

**Issue by ghost** [fsharplang-ru/pulsar-client-dotnet#115]
Hello,

Using C# and trying to cancel some of the async methods and am having issues since the async methods can't be cancelled.

I would like to be able to do something like this

```
var cancellationToken = new CancellationTokenSource().Token;
await consumer.ReceiveAsync(cancellationToken);
```

Thanks.

**Comment by Lanayx** [comment]
@Suchere Hi! Can you please provide your use case for better understanding, why do you want to cancel the receive? If you want to stop  consuming you can call DisposeAsync or UnsubscribeAsync depending on your needs, it will cancel the receive.

**Comment by ghost** [comment]
@Lanayx Thanks for the quick reply!

I want to cancel the receive because I am working in a sync context so the thread is blocked and I can't call unsubscribe.
I think I will offload the receive in a Task.Run so I can manually check the status of the task and call unsubscribe if the cancellation token has expired, thanks.

1. I was wondering if it's a 'heavy' operation to subscribe/unsubscribe just for the use case of cancelling the receive operation?
2. Is there a way to check a consumer's current status (like checking whether it is currently subscribed or not) ?

**Comment by Lanayx** [comment]
@Suchere I just wanted to understand why would you want to stop receiving without stoping the consumer itself. Consumer should be treated as a separate process, it fetches messages in background and stores in internal queue. So when ReceiveAsync is called it either just simply returns the messages from the queue or waits for the new message to arrive. The DisposeAsync stops the consumer without ability to resubscribe (this answers your second question, since it is always subscribed until disposed or reached end of the topic, which is another story). UnsubscribeAsync does DisposeAsync plus resets the subscription in broker, so neither of those methods allow to reuse the same consumer after disposing, you'll need to create a new consumer each time, this is a quite expensive operation.
As far as I see you want to have a way to cancel receive for some reason without closing consumer to continue later. But it looks like you can accomplish it without adding cancellation support to the library, you just store the Task and await as long as you want, then you can cancel your awaiter when needed. Then some time later you can await the stored Task from another thread.
Saying that, I will think on adding cancellation support to the library, since it seems quite easy to implement - all needed is just checking this token right before completing the task with the resulting message, this won't really "cancel" the receive, but will give this message to another waiter while completing the cancelled task with exception.

**Comment by ghost** [comment]
@Lanayx 

> I just wanted to understand why would you want to stop receiving without stoping the consumer itself.

I want to use the same consumer but be able to control when I am receiving e.g. user clicking start and stop button on a UI. Reading the rest of your comment, looks like I should be creating a new consumer every time I want to receive and disposing when I'm done.

---

> Saying that, I will think on adding cancellation support to the library, since it seems quite easy to implement - all needed is just checking this token right before completing the task with the resulting message, this won't really "cancel" the receive, but will give this message to another waiter while completing the cancelled task with exception.

I look forward to this, thanks. I'm wondering whether it will ever reach the point where it checks the cancellation token's status if a message is never received? If the task is complete, hasn't it stopped receiving then?

**Comment by Lanayx** [comment]
>  I'm wondering whether it will ever reach the point where it checks the cancellation token's status if a message is never received? If the task is complete, hasn't it stopped receiving then?

You are right, it will never stop receiving if message never comes, but it is a problem? Could you post an example of code of how you plan to stop and resume receiving messaging, what issues do you encounter, maybe you don't need cancellation token at all, or the proposed solution with Task saving could work. With UI example you don't need cancellation, just after clicking stop you set the stop flag and after receive completes you can check the flag and do negative acknowledge instead of acknowledge (or even simpler save the result to display first after clicking enable button)

**Comment by ghost** [comment]
```
    class Program
    {
        static void Main(string[] args)
        {
            var client = new PulsarClientBuilder()
                .ServiceUrl("")
                .Build();

            var consumer = client.NewConsumer()
                .SubscribeAsync()
                .GetAwaiter().GetResult();

            var token = new CancellationTokenSource(10000);
            var task = Task.Run(() => Fetch(consumer));

            while (!task.IsCompleted)
            {
                if (token.IsCancellationRequested)
                {
                    consumer.UnsubscribeAsync();
                }
            }

            if (task.IsFaulted || task.IsCanceled)
            {
                //This is where the receive was cancelled... do whatever
                return;
            }

            if (task.Status == TaskStatus.RanToCompletion)
            {
                var msg = task.Result;
                //do whatever i want with the message now
            }
        }

        private static async Task<Message<byte[]>> Fetch(IConsumer<byte[]> consumer)
        {
            try
            {
                return await consumer.ReceiveAsync();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
```

I plan on doing **something** like the above... haven't tried it.

Lets say that in my application, I want to receive on demand (I can stop and start it whenever), there would be no way to stop ` Task.Run(() => Fetch(consumer));` without a proper cancellation token. Seems like the solution you suggested with the cancellation token would still cause the task to carry on running if no message is ever consumed in the first place.

**Comment by Lanayx** [comment]
@Suchere In you example you are trying to receive just one message, was that your intention? If not, then let's say token is implemented (so receive will throw task cancelled exception), can you show how you plan to do 3 things: receiving messages in a loop and using those messages, stopping consuming and resuming the message loop.

**Comment by ghost** [comment]
@Lanayx 

> In you example you are trying to receive just one message, was that your intention?

Just for this example, yes, to show how I would plan on doing things.
In reality, I am working on a service that has a thread that loops continuously with a cancellation token. The receive call is blocking since it will wait forever if no message arrives... this is problematic since I can't control the thread. Disposing the consumer just to stop receiving doesn't make sense if you want to selectively choose when to receive.

I believe the Java and Python clients allow timeouts (Java one here: http://pulsar.apache.org/api/client/org/apache/pulsar/client/api/Consumer.html#receive-int-java.util.concurrent.TimeUnit-)

It would be a nice bonus to have cancellation token support for every async method.

I am mostly running into problems writing tests where I want to receive for _x_ amount of time. If nothing is received, the call ends up to be blocking which causes the test to hang. I really don't want to have the hacky way of doing it by disposing the consumer.

---

> can you show how you plan to do 3 things: receiving messages in a loop and using those messages, stopping consuming and resuming the message loop.

Lets say there is a Windows Form Application. Two buttons, one to start receiving and one to stop... both would control the cancellation token for a receiving thread to use for looping. The looping thread would be able to use the cancellation token manipulated by the start/stop buttons in the consumer receive call so that if the stop button is pressed, receiving is cancelled instead of being blocked until a message arrives (or the consumer is disposed of, but we **don't want to recreate the consumer every time we want to receive**).

---

Let me know if I missed anything and/or need to provide more clarification.

**Comment by Lanayx** [comment]
> Lets say there is a Windows Form Application. Two buttons, one to start receiving and one to stop... both would control the cancellation token for a receiving thread to use for looping.

I really wanted to understand how you wanted to code this with cancellation token, you are still welcome to provide the code example for the 3 cases I asked. This is how it looks for me now with just a mutable variable _allowReceiving_:
```
while (true) {
while (allowReceiving) {
     var msg = await consumer.ReceiveAsync();
     if (allowReceiving) {
          process(msg);
          await consumer.AcknowledgeAsync(msg);
     } else {
          await Task.Delay(consumerConfig.AcknowledgementsGroupTime); // let pending acks complete
          await consumer.RedeliverUnacknowledgedMessagesAsync();
     }
}
await Task.Delay(100); // waiting for allowReceiving to become true
}
```
As for integration tests, using Unsubscribe is the best option (it's not the hack), since it will clean up the subscription from broker. I would also say that recreating consumer usually takes less than a second, so if the pause is long enough, this delay is not that important.

**Comment by Lanayx** [comment]
Closing as support added in 1.8.0
