### ISSUE TITLE
Unexpected behavior when seeking and receiving messages in the first batch of the topic

### ISSUE THREAD

**Issue by RobertIndie** [fsharplang-ru/pulsar-client-dotnet#147]
In the dotnet client, when forcing 100 messages to be put into the same batch, and then seek the middle one like 50, it will start receiving from the first message. If batch sending is not enabled or forced to send one by one, it works normally. 

This problem seems to only appear in the first batch of the topic.

Example codes:
```csharp
const string serviceUrl = "pulsar://localhost:6650";

var client = await new PulsarClientBuilder()
    .ServiceUrl(serviceUrl)
    .BuildAsync();

var topicName = "public/default/topic-" + Guid.NewGuid().ToString("N");
logger.WriteLine(topicName);

var producer = await client.NewProducer()
    .Topic(topicName)
    .EnableBatching(true)
    .BatchingMaxPublishDelay(TimeSpan.FromSeconds(3))
    .CreateAsync();

var consumer = await client.NewConsumer()
    .Topic(topicName)
    .SubscriptionName("test-subscription")
    .SubscribeAsync();

// Act
int num = 100;
List<MessageId> msgs = new List<MessageId>(num);
List<Task<MessageId>> tasks = new List<Task<MessageId>>();

// When uncomment this, it will send the first batch, and the problem will not appear in the following batches.
// await producer.SendAsync(Encoding.UTF8.GetBytes("first-batch-message"));

for (int i = 0; i < num; i++)
{
    tasks.Add(producer.SendAsync(
        Encoding.UTF8.GetBytes($"[{i}]")));
}

await Task.WhenAll(tasks); // Force 100 messages to be sent in the same batch.
foreach (var task in tasks)
{
    msgs.Add(await task);
}

await consumer.SeekAsync(msgs[50]);

for (int i = 0; i < 10; i++)
{
    var reMsg = await consumer.ReceiveAsync();
    String msg = Encoding.UTF8.GetString(reMsg.Data);
    logger.WriteLine(msg);
}
```

Running these codes will output:
```
public/default/topic-215bd2ac57be47729b233b77695e2eb7
[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
```

When uncommenting the line `await producer.SendAsync(Encoding.UTF8.GetBytes("first-batch-message"));` to send the first batch first. It will output the expected result.
Expected output:
```
public/default/topic-215bd2ac57be47729b233b77695e2eb7
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]

```

**Comment by Lanayx** [comment]
Hi, @RobertIndie! Have you enabled batch index acknowledgement on server side?

**Comment by RobertIndie** [comment]
> Hi, @RobertIndie! Have you enabled batch index acknowledgement on server side?

Do you mean `acknowledgmentAtBatchIndexLevelEnabled` in `broker.conf`? I have set it as the default value `false`.

**Comment by Lanayx** [comment]
Nevermind, I initially though this has something to to with acknowledgmentAtBatchIndexLevelEnabled, but the issue is that SeekAsync happens after messages were sent from broker to consumer, but before they landed in internal queue. I'll see how to do the workaround, but I think that Java client must be vulnerable to this as well.

**Comment by RobertIndie** [comment]
I have tested it in the Java client, and the same code does not have such a problem in the Java client.

**Comment by Lanayx** [comment]
In java it works by pure luck :) There messages appear in the queue before the moment seek response is done, this is because in Java internal message queue is not blocked while waiting for the seek response, so messages usually win during this race condition. In 99.9% cases it will work fine, but sometimes can fail.

**Comment by Lanayx** [comment]
I've just published 2.0.2, it should fix the issue, can you please check?

**Comment by RobertIndie** [comment]
Thank you! It works.

**Comment by Lanayx** [comment]
@RobertIndie Nice to hear! Please don't forget to star the project if you find it useful :)

**Comment by RobertIndie** [comment]
> In java it works by pure luck :) There messages appear in the queue before the moment seek response is done, this is because in Java internal message queue is not blocked while waiting for the seek response, so messages usually win during this race condition. In 99.9% cases it will work fine, but sometimes can fail.

Hi @Lanayx , do you know where the race condition is in the java client? Can we fix this problem?

**Comment by Lanayx** [comment]
@RobertIndie, the process is the following
1. User calls Seek method
2. Client sends Seek request
3. Client receives Seek response
4. Client clears incoming messages queue
5. Client returns Seek result to User
6. Client receives Reconnect message and starts reconnecting.

I see two possible issues here:
- If message is received by Client before step 4 it will be processed by User even though the Seek is in progress.
- If message is received by Client between 5 and 6 steps we'll see exactly the same issue as you posted here.
The fix that I made is set startMessageId on step 4, so messages that arrive before Reconnect are ignored - this is a shortest way to fix it, but a bit hacky (since it seems that seekMessageId is no longer needed). Another way I can imagine the fix - to compare incoming messages not just with startMessageId, but with seekMessageId as well.

**Comment by RobertIndie** [comment]
Thanks for your replying.

In the java client, it has already reset the `startMessageId` when reconnecting to the broker. (in https://github.com/apache/pulsar/blob/935cedaac9cc6d501bb50ff6c65e8ecf328485c4/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L820 and https://github.com/apache/pulsar/blob/935cedaac9cc6d501bb50ff6c65e8ecf328485c4/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L705).

It seems to be able to achieve the same effect as you have fixed.

**Comment by Lanayx** [comment]
@RobertIndie Yes, I'm aware of that :) That's why I wrote "If message is received by Client **between** 5 and 6 steps", which is before that logic happens
