### ISSUE TITLE
Mock IConsumer in a unit test

### ISSUE THREAD

**Issue by tgrieger-sf** [fsharplang-ru/pulsar-client-dotnet#159]
I'm trying to find a way to mock IConsumer's RecieveAsync method call but I can't figure out how to create a Message to return in the mocked call. Am I missing something or is the only way to create a Message internal to the pulsar client? Or is there a better way to mock an IConsumer (and other interfaces)?

**Comment by Lanayx** [comment]
Hi! You shouldn't mock interfaces and classes from library, rather create your own abstractions and mock them. IConsumer is an interface for only one reason - there are different implementations of it depending on the topic type.

**Comment by tgrieger-sf** [comment]
Thanks for the answer. Out of curiosity, was there a design reason for making it that way? Has there ever been any thought to putting an interface on top of the Message object as well?

**Comment by Lanayx** [comment]
There is no big point in it, since "abstractions must be owned by their consumers" https://mobile.twitter.com/Tyrrrz/status/1312407616295927813 . You should always do it on your side, since if the library changes interface api for some reason - your program will  break in just one place, where you convert message to your abstraction.

**Comment by tgrieger-sf** [comment]
Makes sense. Thanks for discussing with me.
