### ISSUE TITLE
Producer issues with SendAndForgetAsync

### ISSUE THREAD

**Issue by bonza** [fsharplang-ru/pulsar-client-dotnet#276]
Hello! 

First of all, thank you for your work and a great library to work with Pulsar.

While testing the Key Shared subscription I discovered a weird behavior of consumers, when consumers did not respect the key, i.e. messages with the same key were received by different consumers. 

The example code to reproduce the issue is here https://github.com/bonza/pulsar.test/tree/main

After some experiments, I noticed that adding a `Thread.Sleep()` right after [sending the message](https://github.com/bonza/pulsar.test/blob/main/Pulsar.Producer/Program.cs#L65) fixed the issue, as well as using `SendAsync`instead of `SendAndForgetAsync` (see the code in the [working branch](https://github.com/bonza/pulsar.test/blob/working/Pulsar.Producer/Program.cs))

I'm not well-versed in Pulsar, but I'm curious whether this behavior of the `SendAndForgetAsync` method is intentional or a bug.

**Comment by Lanayx** [comment]
Hi, it looks like you want to use key based batch builder in producer configuration https://github.com/fsprojects/pulsar-client-dotnet/blob/0207eba160ab471c6c30348976b3c88922ea13fc/src/Pulsar.Client/Common/DTO.fs#L115. SendAndForget is much faster, because it doesn't wait for broker confirmation and thus enables easy way to do batches.

**Comment by bonza** [comment]
Thanks a lot, that worked!
